#!/bin/bash


while read line
do
    keywords=`echo "$line" | sed -re "" \
    -e "s/^(while)( .*)/#\1#\2/g" -e "s/(.* )(while)( .*)/\1#\2#\3/g" \
    -e "s/^(volatile)( .*)/#\1#\2/g" -e "s/(.* )(volatile)( .*)/\1#\2#\3/g" \
    -e "s/^(void)( .*)/#\1#\2/g" -e "s/(.* )(void)( .*)/\1#\2#\3/g" \
    -e "s/^(unsigned)( .*)/#\1#\2/g" -e "s/(.* )(unsigned)( .*)/\1#\2#\3/g" \
    -e "s/^(union)( .*)/#\1#\2/g" -e "s/(.* )(union)( .*)/\1#\2#\3/g" \
    -e "s/^(typedef)( .*)/#\1#\2/g" -e "s/(.* )(typedef)( .*)/\1#\2#\3/g" \
    -e "s/^(switch)( .*)/#\1#\2/g" -e "s/(.* )(switch)( .*)/\1#\2#\3/g" \
    -e "s/^(struct)( .*)/#\1#\2/g" -e "s/(.* )(struct)( .*)/\1#\2#\3/g" \
    -e "s/^(static)( .*)/#\1#\2/g" -e "s/(.* )(static)( .*)/\1#\2#\3/g" \
    -e "s/^(sizeof)( .*)/#\1#\2/g" -e "s/(.* )(sizeof)( .*)/\1#\2#\3/g" \
    -e "s/^(signed)( .*)/#\1#\2/g" -e "s/(.* )(signed)( .*)/\1#\2#\3/g" \
    -e "s/^(short)( .*)/#\1#\2/g" -e "s/(.* )(short)( .*)/\1#\2#\3/g" \
    -e "s/^(return)( .*)/#\1#\2/g" -e "s/(.* )(return)( .*)/\1#\2#\3/g" \
    -e "s/^(register)( .*)/#\1#\2/g" -e "s/(.* )(register)( .*)/\1#\2#\3/g" \
    -e "s/^(long)( .*)/#\1#\2/g" -e "s/(.* )(long)( .*)/\1#\2#\3/g" \
    -e "s/^(int)( .*)/#\1#\2/g" -e "s/(.* )(int)( .*)/\1#\2#\3/g" \
    -e "s/^(if)( .*)/#\1#\2/g" -e "s/(.* )(if)( .*)/\1#\2#\3/g" \
    -e "s/^(goto)( .*)/#\1#\2/g" -e "s/(.* )(goto)( .*)/\1#\2#\3/g" \
    -e "s/^(for)( .*)/#\1#\2/g" -e "s/(.* )(for)( .*)/\1#\2#\3/g" \
    -e "s/^(float)( .*)/#\1#\2/g" -e "s/(.* )(float)( .*)/\1#\2#\3/g" \
    -e "s/^(extern)( .*)/#\1#\2/g" -e "s/(.* )(extern)( .*)/\1#\2#\3/g" \
    -e "s/^(enum)( .*)/#\1#\2/g" -e "s/(.* )(enum)( .*)/\1#\2#\3/g" \
    -e "s/^(else)( .*)/#\1#\2/g" -e "s/(.* )(else)( .*)/\1#\2#\3/g" \
    -e "s/^(double)( .*)/#\1#\2/g" -e "s/(.* )(double)( .*)/\1#\2#\3/g" \
    -e "s/^(do)( .*)/#\1#\2/g" -e "s/(.* )(do)( .*)/\1#\2#\3/g" \
    -e "s/^(default)( .*)/#\1#\2/g" -e "s/(.* )(default)( .*)/\1#\2#\3/g" \
    -e "s/^(continue)( .*)/#\1#\2/g" -e "s/(.* )(continue)( .*)/\1#\2#\3/g" \
    -e "s/^(const)( .*)/#\1#\2/g" -e "s/(.* )(const)( .*)/\1#\2#\3/g" \
    -e "s/^(char)( .*)/#\1#\2/g" -e "s/(.* )(char)( .*)/\1#\2#\3/g" \
    -e "s/^(case)( .*)/#\1#\2/g" -e "s/(.* )(case)( .*)/\1#\2#\3/g" \
    -e "s/^(break)( .*)/#\1#\2/g" -e "s/(.* )(break)( .*)/\1#\2#\3/g" \
    -e "s/^(auto)( .*)/#\1#\2/g" -e "s/(.* )(auto)( .*)/\1#\2#\3/g" #\
#    -e "s/([ (<>=]+)(\"[^\"]*\")|([a-z_][a-zA-Z0-9_]*)([, =;()<>]+)/\1\2^\3^\4/g"
    `

    #regexQuote='(^[^"])("[^"]")(.*)'
    #regexQuote='(.*)'
    while true
    do
        if [[ $keywords =~ $regexQuote ]] 
        then
            echo "${BASH_REMATCH[1]}"
            break
        else
            echo "FOUND NO MATCHES"
            break
        fi
    done
done


